version: '3.8'

services:
  # ML-сервис прогнозирования дефолта
  ml-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: credit_default_api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      # Монтирование директории с логами для анализа A/B-теста
      - ./../models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
